server:
  port: 9071
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9070/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: zuul-client1
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2500MB
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000