server:
    port: 9023
eureka:
    client:
        service-url:
            defaultZone: http://localhost:9020/eureka/
    instance:
        prefer-ip-address: true
spring:
    application:
        name: ribbon-web
ribbon-client:
    ribbon:
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
