server:
  port: 9080
spring:
  application:
    name: sprirngcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengkai02/springcloud-config-server
          username: xju_zk@163.com
          password: 122090401762.up